[server]

# The port where the server will listen for browser connections.
# Don't use port 3000 which is reserved for internal development.
# Default: 8501
port = 8501

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 1000

# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 1000
